# Generated by Django 4.2.29 on 2026-03-05 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('duretion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='genre_track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.track')),
            ],
        ),
    ]
