# Generated by Django 4.2.28 on 2026-04-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_artist_track_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artists',
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artist'),
        ),
    ]
